apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  # push: false
  googleCloudBuild:
    projectId: ticketing-dev-300713
  artifacts:
    - image: us.gcr.io/ticketing-dev-300713/auth # gcp_url/project_id/project_directory
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.gcr.io/ticketing-dev-300713/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.{ts,tsx}"
            dest: .
    - image: us.gcr.io/ticketing-dev-300713/deals
      context: deals
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
