apiVersion: apps/v1
kind: Deployment
metadata:
  name: deals-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deals #metadata의 label과 일치해야함
  template:
    metadata:
      labels:
        app: deals
    spec:
      containers:
        - name: deals
          image: us.gcr.io/ticketing-dev-300713/deals
          env:
            - name: MONGO_URI
              value: "mongodb://deals-mongo-srv:27017/deals"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: deals-srv
spec:
  selector:
    app: deals #label과 일치해야함
  ports:
    - name: deals
      protocol: TCP
      port: 3000
      targetPort: 3000
